### ISSUE TITLE
unable to run tests

### ISSUE THREAD

**Issue by dmitmel** [rickyhan/xprite-editor#8]
When trying to run `cargo test` in the `xprite` crate, I get the following error:

```
error[E0061]: this function takes 4 parameters but 3 parameters were supplied
  --> xprite/src/algorithms/selective_antialias.rs:54:9
   |
5  | pub fn selective_antialias(path: &mut Pixels, k: f64, alt_color: Color, min_segment_length: usize) {
   | -------------------------------------------------------------------------------------------------- defined here
...
54 |         selective_antialias(&mut path, 0.5, Color::orange());
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 4 parameters
```.

**Comment by rickyhan** [comment]
This used to a bug but now it should be fixed in the latest master. Could you confirm you are testing the latest version? Thanks for checking xprite out!

**Comment by dmitmel** [comment]
Yep, building from commit `7f899df` works and tests compile without any problems. I was packaging v0.1.0 for AUR (Arch User Repository), that's why I saw this issue.
